services:
  app:
    container_name: flask_container
    build:
      context: .
    ports:
      - "8080:5000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.4
    container_name: mysql_container
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - ./database/initialize:/docker-entrypoint-initdb.d
      - ./database/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD"
      interval: 1s
      retries: 3
